version: 2
jobs:
  first_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10
  second_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two   
